USE LineyschikovCoreContext
GO

SET IDENTITY_INSERT [dbo].[Customers] ON
INSERT INTO [dbo].[Customers] ([Id], [Name], [Address], [Vip]) VALUES (1, N'Антон Александрович', N'Таганская', 0)
INSERT INTO [dbo].[Customers] ([Id], [Name], [Address], [Vip]) VALUES (2, N'Валентина Андреевна', N'Автозаводская', 0)
INSERT INTO [dbo].[Customers] ([Id], [Name], [Address], [Vip]) VALUES (3, N'Евгений Владимирович', N'Теплый стан', 1)
INSERT INTO [dbo].[Customers] ([Id], [Name], [Address], [Vip]) VALUES (4, N'Татьяна Вячеславовна', N'Планерная', 0)
INSERT INTO [dbo].[Customers] ([Id], [Name], [Address], [Vip]) VALUES (5, N'Аркадий Дмитриевич', N'Лубянка', 1)
INSERT INTO [dbo].[Customers] ([Id], [Name], [Address], [Vip]) VALUES (6, N'Светлана Артемьевна', N'Тропарево', 0)
INSERT INTO [dbo].[Customers] ([Id], [Name], [Address], [Vip]) VALUES (7, N'Михаил Константинович', N'Воробьевы горы', 1)
INSERT INTO [dbo].[Customers] ([Id], [Name], [Address], [Vip]) VALUES (8, N'Анастасия Андреевна', N'Охотный ряд', 0)
INSERT INTO [dbo].[Customers] ([Id], [Name], [Address], [Vip]) VALUES (9, N'Петр Григорьевич', N'Павелецкая', 0)
SET IDENTITY_INSERT [dbo].[Customers] OFF

SET IDENTITY_INSERT [dbo].[Orders] ON
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (1, N'Небольшой заказ', 1)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (2, N'Важный заказ', 1)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (3, N'Новый заказ', 1)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (4, N'Отмененный заказ 1', 1)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (5, N'Отмененный заказ 2', 1)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (6, N'Крупный заказ', 2)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (7, N'Приоритетный заказ', 2)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (8, N'Отложенный заказ 1', 2)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (9, N'Отложенный заказ 2', 2)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (10, N'Отложенный заказ 3', 2)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (11, N'Срочный заказ', 3)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (12, N'Выполненный заказ', 3)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (13, N'Закрытый заказ 1', 3)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (14, N'Закрытый заказ 2', 3)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (15, N'Закрытый заказ 3', 3)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (16, N'Старый заказ', 4)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (17, N'Новый заказ А', 4)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (18, N'Новый заказ Б', 4)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (19, N'Новый заказ В', 4)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (20, N'Последний заказ', 4)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (21, N'Большой заказ', 5)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (22, N'Выполненный заказ', 5)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (23, N'Срочный заказ', 6)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (24, N'Большой заказ А', 6)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (25, N'Большой заказ Б', 6)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (26, N'Закрытый заказ', 7)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (27, N'Просроченный заказ 1', 7)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (28, N'Просроченный заказ 2', 7)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (29, N'Отмененный заказ', 8)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (30, N'Закрытый заказ', 8)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (31, N'Срочный заказ', 8)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (32, N'Срочный заказ 1', 9)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (33, N'Срочный заказ 2', 9)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (34, N'Срочный заказ 3', 9)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (35, N'Выполненный заказ 1', 9)
INSERT INTO [dbo].[Orders] ([Id], [Description], [CustomerId]) VALUES (36, N'Выполненный заказ 2', 9)
SET IDENTITY_INSERT [dbo].[Orders] OFF
